spring:
  profiles:
    active: dev #we can active many profile by seperated commas

  mail:
    host: smtp.gmail.com
    port: 587
    username: ujjwal.dey55@gmail.com
    password: "xxxx xxxx xxxx xxxx"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



logging:
  level:
    ## root: OFF ## this will ensure the logging rule applicable for all level
    com:
      example:
        ## Dubug and more severity log enable for journal app package only
        journalApp: DEBUG

weather:
  api:
    key: "0098e097dd64e3d72c5f4632c70f6dd3"
